apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: janusgraph-banking

resources:
  - namespace.yml
  - rbac.yml
  - configmaps.yml
  - secrets.yml
  - janusgraph-deployment.yml
  - api-deployment.yml
  - network-policy.yml

commonLabels:
  app.kubernetes.io/part-of: janusgraph-banking
  app.kubernetes.io/managed-by: kustomize
