apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-default
  namespace: janusgraph-banking
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-to-janusgraph
  namespace: janusgraph-banking
spec:
  podSelector:
    matchLabels:
      app: janusgraph
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: banking-api
      ports:
        - port: 8182
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-ingress
  namespace: janusgraph-banking
spec:
  podSelector:
    matchLabels:
      app: banking-api
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 8001
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-egress
  namespace: janusgraph-banking
spec:
  podSelector:
    matchLabels:
      app: banking-api
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: janusgraph
      ports:
        - port: 8182
    - to:
        - podSelector:
            matchLabels:
              app: opensearch
      ports:
        - port: 9200
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
