# File: .github/ISSUE_TEMPLATE/config.yml
# Created: 2026-01-28T10:31:20.567
# Author: David LECONTE - IBM Worldwide | Data & AI | Tiger Team | Data Watstonx.Data Global Product Specialist (GPS)

blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/davidleconte/hcd-janusgraph/wiki
    about: Check documentation for help
  - name: Security Issue
    url: https://github.com/davidleconte/hcd-janusgraph/security
    about: Report security vulnerabilities
