apiVersion: v1
kind: ConfigMap
metadata:
  name: janusgraph-config
  namespace: janusgraph-banking
data:
  janusgraph-cql-server.properties: |
    gremlin.graph=org.janusgraph.core.JanusGraphFactory
    storage.backend=cql
    storage.hostname=hcd-server
    storage.cql.keyspace=janusgraph
    cache.db-cache=true
    cache.db-cache-clean-wait=20
    cache.db-cache-time=180000
    cache.db-cache-size=0.25
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
  namespace: janusgraph-banking
data:
  janusgraph-use-ssl: "false"
  cors-origins: "http://localhost:3000,http://localhost:8080"
